[package]
name = "Rustic64"
version = "0.1.1"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
